In [44]:
import pandas as pd
import numpy as np

In [45]:
df = pd.read_csv("datasets\\solder_ball_conc.csv", index_col=0)
df

,d_pad,t_pad,d_us,d_rep1,t_ubm,del_d,h_ball,max_conc,min_conc
0,150.319657,17.594015,218.488558,145.651512,7.939269,19.293996,154.776285,1.028214,0.934331
1,177.052630,22.348553,189.272172,98.928538,10.941862,12.235633,162.905175,1.031436,0.951577
2,165.164897,18.236923,182.819857,64.621469,11.109719,31.196611,143.936878,1.052080,0.934824
3,159.789155,23.169296,202.797451,54.344873,13.706429,34.519487,149.092097,1.038364,0.927828
4,172.055325,28.539006,188.789397,156.365151,8.258886,31.570212,146.819781,1.059355,0.951765
...,...,...,...,...,...,...,...,...,...
95,170.396025,17.302672,212.142721,95.484023,9.966557,10.243406,156.924139,1.043699,0.935675
96,153.458441,20.942815,219.385411,100.295889,11.395604,26.628325,154.305706,1.030681,0.920680
97,152.950176,24.641168,205.988236,43.816815,14.930168,23.691754,163.931621,1.050186,0.932844
98,173.022438,24.316004,197.090875,104.214214,5.154746,33.305723,162.467775,1.029669,0.949575
99,161.947216,16.177490,188.381989,84.854512,5.228543,14.704528,153.906935,1.043221,0.938941

In [46]:
names = [
    "d_pad",
    "t_pad",
    "d_us",
    "d_rep1",
    "t_ubm",
    "del_d",
    "h_ball",
]

X_bounds = np.array(
    [
        [150.0, 180.0],
        [15.0, 30.0],
        [180.0, 220.0],
        [30.0, 160.0],
        [5.0, 15.0],
        [10.0, 40.0],
        [130.0, 165.0],
    ]
)

df_X_scaled = (df[names] - X_bounds[:, 0]) / (X_bounds[:, 1] - X_bounds[:, 0])
df_y_scaled = (df["max_conc"] - df["max_conc"].mean()) / df["max_conc"].std()

In [47]:
df_X_scaled

       d_pad     t_pad      d_us    d_rep1     t_ubm     del_d    h_ball
0   0.010655  0.172934  0.962214  0.889627  0.293927  0.309800  0.707894
1   0.901754  0.489904  0.231804  0.530220  0.594186  0.074521  0.940148
2   0.505497  0.215795  0.070496  0.266319  0.610972  0.706554  0.398197
3   0.326305  0.544620  0.569936  0.187268  0.870643  0.817316  0.545488
4   0.735177  0.902600  0.219735  0.972040  0.325889  0.719007  0.480565
..       ...       ...       ...       ...       ...       ...       ...
95  0.679867  0.153511  0.803568  0.503723  0.496656  0.008114  0.769261
96  0.115281  0.396188  0.984635  0.540738  0.639560  0.554278  0.694449
97  0.098339  0.642745  0.649706  0.106283  0.993017  0.456392  0.969475
98  0.767415  0.621067  0.427272  0.570879  0.015475  0.776857  0.927651
99  0.398241  0.078499  0.209550  0.421958  0.022854  0.156818  0.683055

[100 rows x 7 columns]

In [57]:
df_X_scaled.iloc[df_y_scaled[df_y_scaled < -1].index].mean(axis=0)

d_pad     0.489573
t_pad     0.609545
d_us      0.418431
d_rep1    0.699515
t_ubm     0.421803
del_d     0.367529
h_ball    0.481834
dtype: float64