In [3]:
import pandas as pd

with pd.ExcelFile("stresstool_update.xls") as xls:
    df0 = pd.read_excel(xls, "UserInterface")
    df1 = pd.read_excel(xls, "Kriging")
    df2 = pd.read_excel(xls, "Quadratic")

In [4]:
df0

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,CFT T&MA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Design Tool SOT428,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Critical Die Stress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,This tool is based on 2D FEM simulations,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Specification,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,die thickness,NaN,NaN,0.24,mm,,NaN,NaN,NaN,0
11,NaN,NaN,NaN,130,NaN,NaN,NaN,NaN,NaN,NaN
12,solder thickness,NaN,NaN,0.05,mm,,NaN,NaN,NaN,0
13,NaN,NaN,NaN,5,unit1unit,NaN,NaN,NaN,NaN,NaN
14,lead frame thickness,NaN,NaN,0.2,mm,,NaN,NaN,NaN,0
15,NaN,NaN,NaN,"1,.0",NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
17,Nominal Tensile Stress = +150 MPa,NaN,NaN,NaN,NaN,NaN,Nominal Compressive Stress = -600 MPa,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Results: Die Stress Values,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,MidDieStress,NaN,MaxDieStress,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,RSM -1,Top,NaN,NaN,NaN,196.520549,MPa,198.353865,MPa,CRITICAL STRESS
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,Bottom,NaN,NaN,NaN,-318.843536,MPa,-318.775443,MPa,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,RSM-2,Top,NaN,NaN,NaN,28.025882,MPa,27.649469,MPa,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,Bottom,NaN,NaN,NaN,-33.772495,MPa,-40.864539,MPa,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,RSM-3,Top,NaN,NaN,NaN,-452.684034,MPa,-472.078726,MPa,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,Bottom,NaN,NaN,NaN,-434.839191,MPa,-434.849139,MPa,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,RSM-4,Top,NaN,NaN,NaN,-56.409,MPa,-111.190004,MPa,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,Bottom,NaN,NaN,NaN,-254.634732,MPa,-45.511629,MPa,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,RSM-5,Top,NaN,NaN,NaN,-49.270943,MPa,-309.078794,MPa,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,Bottom,NaN,NaN,NaN,-259.240324,MPa,-264.209053,MPa,NaN
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,For any remarks or questions regarding this ...,NaN,NaN,NaN,NaN,NaN,Willem van Driel,NaN,NaN,NaN
48,"Last updated: Version 0,",NaN,"Nov 9, 2000,",NaN,by Willem van Driel,NaN,NaN,NaN,NaN,NaN

In [5]:
df1

,Unnamed: 0,Determination of die stress using Kriging Models,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,Define input,Parameter,Value,Unity,lowerrange,upperrange,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,die thickness,dt,0.24,mm,0.24,0.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,solder thickness,t_solder,0.05,mm,0.02,0.08,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,lead frame thickness,t_lf,0.2,mm,0.2,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,top2,NaN,NaN,MidDieStress,NaN,NaN,top2,NaN,NaN,MaxDieStress
...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,22,0.233,0.065,-5688.432442,NaN,NaN,-5636.743871,NaN,NaN,-5391.746141,NaN,NaN,-5342.753443
116,23,0.633,0.078,3309.003533,NaN,NaN,2561.123582,NaN,NaN,3248.997542,NaN,NaN,2514.679764
117,24,0.8,0.028,749.509674,NaN,NaN,481.785796,NaN,NaN,617.667652,NaN,NaN,397.037572
118,25,0.333,0.047,-4910.573748,NaN,NaN,-4786.44555,NaN,NaN,-4836.480189,NaN,NaN,-4714.224909
119,NaN,NaN,NaN,NaN,NaN,NaN,-259.240324,NaN,NaN,NaN,NaN,NaN,-264.209053

In [6]:
df2

,Unnamed: 0,Determination of die stress Using Quadratic Models,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,Define input,Parameter,Value,Unity,lowerrange,upperrange,NaN,Calculated coefficients (from COMPACT),NaN,NaN,NaN,NaN,MaxDieStress,NaN
1,die thickness,dt,0.24,mm,0.24,0.24,NaN,NaN,C0,396.3811,NaN,NaN,C0,400.5307
2,solder thickness,t_solder,0.05,mm,0.02,0.08,NaN,NaN,C1,-580.9560,NaN,NaN,C1,-526.0410
3,lead frame thickness,t_lf,0.2,mm,0.2,0.1,NaN,NaN,C2,-1016.9020,NaN,NaN,C2,-1041.3340
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C3,0.0000,NaN,NaN,C3,0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,NaN,(Sigma22=C0+C1*t_solder+C2*t_lf+C3*t_solder^2+...,NaN,NaN,NaN,NaN,NaN,NaN,C1,0.0000,NaN,NaN,C1,0.0000
88,MaxDieStress,Top Die Stress 1,0,MPa,NaN,NaN,NaN,NaN,C2,0.0000,NaN,NaN,C2,0.0000
89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C3,0.0000,NaN,NaN,C3,0.0000
90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C4,0.0000,NaN,NaN,C4,0.0000
91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C5,0.0000,NaN,NaN,C5,0.0000

In [ ]:
import gpytorch

In [ ]:
gpytorch.kernels.RBFKernel()

RBFKernel(
  (raw_lengthscale_constraint): Positive()
)